CREATE SCHEMA IF NOT EXISTS nfse_app;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE  table_schema = 'credito'
        AND    table_name   = 'credito'
    ) THEN
        EXECUTE '
            CREATE TABLE nfse_app.credito (
                id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
                numero_credito    VARCHAR(50) NOT NULL UNIQUE,
                numero_nfse       VARCHAR(50) NOT NULL,
                data_constituicao DATE        NOT NULL,
                valor_issqn       DECIMAL(15, 2) NOT NULL,
                tipo_credito      VARCHAR(50) NOT NULL,
                simples_nacional  BOOLEAN     NOT NULL,
                aliquota          DECIMAL(5, 2)  NOT NULL,
                valor_faturado    DECIMAL(15, 2) NOT NULL,
                valor_deducao     DECIMAL(15, 2) NOT NULL,
                base_calculo      DECIMAL(15, 2) NOT NULL
            );
        ';
    END IF;
END
$$;

INSERT INTO nfse_app.credito (
    numero_credito, numero_nfse, data_constituicao, valor_issqn,
    tipo_credito, simples_nacional, aliquota, valor_faturado, valor_deducao, base_calculo
)
SELECT *
FROM (
    VALUES
        ('123456', '7891011', DATE '2024-02-25', 1500.75, 'ISSQN', true, 5.0, 30000.00, 5000.00, 25000.00),
        ('789012', '7891011', DATE '2024-02-26', 1200.50, 'ISSQN', false, 4.5, 25000.00, 4000.00, 21000.00),
        ('654321', '1122334', DATE '2024-01-15', 800.50, 'Outros', true, 3.5, 20000.00, 3000.00, 17000.00)
) AS v(
    numero_credito, numero_nfse, data_constituicao, valor_issqn,
    tipo_credito, simples_nacional, aliquota, valor_faturado, valor_deducao, base_calculo
)
WHERE NOT EXISTS (
    SELECT 1 FROM nfse_app.credito c WHERE c.numero_credito = v.numero_credito
);

