/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.nobblecrafts.nfse.infrastructure.kafka.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum AvroTipoConsulta implements org.apache.avro.generic.GenericEnumSymbol<AvroTipoConsulta> {
  NFSE, CREDITO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroTipoConsulta\",\"namespace\":\"com.nobblecrafts.nfse.infrastructure.kafka.model.avro\",\"symbols\":[\"NFSE\",\"CREDITO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
