logging:
  level:
    org.hibernate.SQL: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema-h2.sql
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:credito;DB_CLOSE_DELAY=-1;
    username: sa
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        connection:
          provider_disables_autocommit: true