spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:credito;DB_CLOSE_DELAY=-1;
    username: sa
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        connection:
          provider_disables_autocommit: true

kafka-config:
  bootstrap-servers: kafka:29092
  schema-registry-url: http://schema-registry:8081