spring:
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init-schema.sql
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=nfse_app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: nfse_app
        dialect: org.hibernate.dialect.PostgreSQLDialect